# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "monthly"

  # Admin module
  - package-ecosystem: "gomod"
    directory: "/admin"
    schedule:
      interval: "monthly"
    groups:
      default: 
        update-types:
          - patch
          - minor
    post-update-commands:
      - go mod tidy

  # API module
  - package-ecosystem: "gomod"
    directory: "/api"
    schedule:
      interval: "monthly"
    groups:
      default: 
        update-types:
          - patch
          - minor
    post-update-commands:
      - go mod tidy
      
  # Application module
  - package-ecosystem: "gomod"
    directory: "/application"
    schedule:
      interval: "monthly"
    groups:
      default: 
        update-types:
          - patch
          - minor
    post-update-commands:
      - go mod tidy

  # Approval module
  - package-ecosystem: "gomod"
    directory: "/approval"
    schedule:
      interval: "monthly"
    groups:
      default: 
        update-types:
          - patch
          - minor
    post-update-commands:
      - go mod tidy

  # Common module
  - package-ecosystem: "gomod"
    directory: "/common"
    schedule:
      interval: "monthly"
    groups:
      default: 
        update-types:
          - patch
          - minor
    post-update-commands:
      - go mod tidy

  # Common-server module
  - package-ecosystem: "gomod"
    directory: "/common-server"
    schedule:
      interval: "monthly"
    groups:
      default: 
        update-types:
          - patch
          - minor
    post-update-commands:
      - go mod tidy

  # cpapi module
  - package-ecosystem: "gomod"
    directory: "/cpapi"
    schedule:
      interval: "monthly"
    groups:
      default:
        update-types:
          - patch
          - minor
    post-update-commands:
      - go mod tidy

  # File-manager module
  - package-ecosystem: "gomod"
    directory: "/file-manager"
    schedule:
      interval: "monthly"
    groups:
      default: 
        update-types:
          - patch
          - minor
    post-update-commands:
      - go mod tidy

  # Gateway module
  - package-ecosystem: "gomod"
    directory: "/gateway"
    schedule:
      interval: "monthly"
    groups:
      default: 
        update-types:
          - patch
          - minor
    post-update-commands:
      - go mod tidy

  # Identity module
  - package-ecosystem: "gomod"
    directory: "/identity"
    schedule:
      interval: "monthly"
    groups:
      default: 
        update-types:
          - patch
          - minor
    post-update-commands:
      - go mod tidy

  # Organization module
  - package-ecosystem: "gomod"
    directory: "/organization"
    schedule:
      interval: "monthly"
    groups:
      default: 
        update-types:
          - patch
          - minor
    post-update-commands:
      - go mod tidy

  # Rover module
  - package-ecosystem: "gomod"
    directory: "/rover"
    schedule:
      interval: "monthly"
    groups:
      default: 
        update-types:
          - patch
          - minor
    post-update-commands:
      - go mod tidy

  # Rover-ctl module
  - package-ecosystem: "gomod"
    directory: "/rover-ctl"
    schedule:
      interval: "monthly"
    groups:
      default: 
        update-types:
          - patch
          - minor
    post-update-commands:
      - go mod tidy

  # Rover-server module
  - package-ecosystem: "gomod"
    directory: "/rover-server"
    schedule:
      interval: "monthly"
    groups:
      default: 
        update-types:
          - patch
          - minor
    post-update-commands:
      - go mod tidy

  # Secret-manager module
  - package-ecosystem: "gomod"
    directory: "/secret-manager"
    schedule:
      interval: "monthly"
    groups:
      default: 
        update-types:
          - patch
          - minor
    post-update-commands:
      - go mod tidy

  # Route-tester module
  - package-ecosystem: "gomod"
    directory: "/tools/route-tester"
    schedule:
      interval: "monthly"
    groups:
      default:
        update-types:
          - patch
          - minor
    post-update-commands:
      - go mod tidy

  # Snapshotter module
  - package-ecosystem: "gomod"
    directory: "/tools/snapshotter"
    schedule:
      interval: "monthly"
    groups:
      default:
        update-types:
          - patch
          - minor
    post-update-commands:
      - go mod tidy