# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: "gomod"
    schedule:
      interval: "weekly"
    directories: 
      - common
      - common-server
      - secret-manager
      - organization
      - gateway
      - identity
      - admin
      - application
      - api
      - rover
      - approval
    groups:
      minor-updates:
        update-types:
          - patch
          - minor