# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

version: 2

before:
  hooks: []

env:
  - CGO_ENABLED=0
  - GO111MODULE=on

builds:
  - id: common-server
    dir: common-server
    main: cmd/server/server.go
    binary: common-server
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: secret-manager
    dir: secret-manager
    main: cmd/server/server.go
    binary: secret-manager
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE*
      - README*
      - CHANGELOG.md

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  header: >-
    # 🚀 Release {{ .Version }}
  footer: >-

    ---

    ✨🎉

sboms:
  - artifacts: archive

kos: 
  - id: common-server
    build: common-server
    main: .
    working_dir: common-server/cmd/server
    repositories:
      - ghcr.io/telekom/controlplane/common-server
    labels:
      org.opencontainers.image.source: https://github.com/telekom/controlplane
      org.opencontainers.image.version: "{{.Version}}"
    user: 65532:65532
    tags:
      - latest
      - "{{.Tag}}"
      - "{{if not .Prerelease}}stable{{end}}"
    bare: true
  - id: secret-manager
    build: secret-manager
    main: .
    working_dir: secret-manager/cmd/server
    repositories:
      - ghcr.io/telekom/controlplane/secret-manager
    labels:
      org.opencontainers.image.source: https://github.com/telekom/controlplane
      org.opencontainers.image.version: "{{.Version}}"
    user: 65532:65532
    tags:
      - latest
      - "{{.Tag}}"
      - "{{if not .Prerelease}}stable{{end}}"
    bare: true