# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: admin.cp.ei.telekom.de/v1
kind: Zone
metadata:
  name: zone-a
spec:
  teamApis:
    apis: []
  identityProvider:
    admin:
      clientId: admin-cli
      userName: admin
      password: somePassword
    url: https://iris-integration.test.dhei.telekom.de/
  gateway:
    admin:
      clientSecret: someRoverSecret
      url: https://stargate-admin-distcp2-dataplane1.dev.dhei.telekom.de/admin-api
    url: https://stargate-distcp2-dataplane1.dev.dhei.telekom.de/
  redis:
    host: foo
    password: topsecret
    port: 6379
